// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	PostID      int32
	AuthorEmail string
	Post        pgtype.Text
}
