// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	AuthorID int32
	Email    string
}

type Post struct {
	PostID   int32
	Post     pgtype.Text
	AuthorID int32
}
