version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
      MIGRATIONS_DIR: file:///app/schema
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}
